version: 2

models:
  - name: int_annual_production_dedup
    description: >
      Intermediate view that deduplicates well-year rows and aggregates measures.
      Representative attributes are taken from the row with the highest months_in_production.
    columns:
      - name: api_well_number
        description: "API well identifier."
        tests:
          - not_null

      - name: reporting_year
        description: "Reporting year."
        tests:
          - not_null

      - name: months_in_production
        description: "Capped to 12 after aggregation."
        tests:
          - between_inclusive:
              min_value: 0
              max_value: 12

      - name: oil_produced_bbl
        description: "Aggregated oil (bbl) per well-year."
        tests:
          - non_negative

      - name: gas_produced_mcf
        description: "Aggregated gas (Mcf) per well-year."
        tests:
          - non_negative

      - name: water_produced_bbl
        description: "Aggregated water (bbl) per well-year."
        tests:
          - non_negative

  - name: dim_year
    description: >
      Year dimension derived from years present in INT. Provides convenience flags
      for current year, last 5 years, and decade bucketing.
    columns:
      - name: year_sk
        description: "Surrogate/business key for the year (same as reporting_year)."
        tests:
          - not_null
          - unique

      - name: year
        description: "Alias of year_sk for readability."
        tests:
          - not_null

      - name: is_current_year
        description: "True if equals current_date() year in Snowflake."

      - name: is_last_5_years
        description: "True if within the last 5 years relative to current_date()."

      - name: decade_start
        description: "Start of the decade (e.g., 2010)."
        tests:
          - not_null

      - name: decade_label
        description: "Text label for decade (e.g., '2010s')."

  - name: dim_well
    description: >
      One row per well. Representative attributes are selected via ranking
      (months_in_production desc, measures sum desc, reporting_year desc).
      Lifetime measures are totals across all years in INT.
    columns:
      - name: well_sk
        description: "Deterministic surrogate key (md5 hex) of api_well_number."
        tests:
          - not_null
          - unique

      - name: api_well_number
        description: "API well identifier (business key)."
        tests:
          - not_null
          - unique

      - name: first_year
        description: "First reporting year observed for the well."
        tests:
          - not_null

      - name: last_year
        description: "Last reporting year observed for the well."
        tests:
          - not_null

      - name: lifetime_oil_bbl
        description: "Total oil produced (bbl) across all years."
        tests:
          - non_negative

      - name: lifetime_gas_mcf
        description: "Total gas produced (Mcf) across all years."
        tests:
          - non_negative

      - name: lifetime_water_bbl
        description: "Total water produced (bbl) across all years."
        tests:
          - non_negative

      - name: well_status_code
        description: "Well status code."
        tests:
          - relationships:
              to: ref('refdata_well_status_codes')
              field: status_code
              severity: warn

      - name: well_type_code
        description: "Well type code."
        tests:
          - relationships:
              to: ref('refdata_well_type_codes')
              field: type_code
              severity: warn
